### PR TITLE
Updating famous.json to include Michael Jordan

### PR DESCRIPTION
**Pull request by calebloughrin**

### CODE REVIEW

**Comment by ArieBeresteanu** [comment]
I suggest you synchronize your forked repository with mine before making a pull request - to avoid conflicts.

**Comment by calebloughrin** [comment]
I have just fetched the upstream to synchronize my forked repository with yours. Do I need to send a new pull request now?

**Comment by ArieBeresteanu** [comment]
Great addition!

**Comment by ArieBeresteanu** [comment]
No, I accepted your pull request. Michael Jordan is in.
Arie

4529 W.W. Posvar Hall
Department of Economics
University of Pittsburgh
www.pitt.edu/~arie
________________________________

**Pull request merged**
